# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Enterprise Integrator Documentation
site_description: Documentation for WSO2 Enterprise Integrator
site_author: WSO2
site_url: https://wso2.com/integration/

# Repository
repo_name: wso2/docs-ei
repo_url: https://github.com/wso2/docs-ei
edit_uri: https://github.com/wso2/docs-ei/edit/master/en/docs/

# Copyright
copyright: WSO2 Enterprise Integrator - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'
  
# Navigation
nav:
    - Introduction:
      - 'Overview': 'intro/overview.md'
      - 'Architecture': 'intro/architecture.md'
      - 'About this Release': 'intro/about_this_release.md'
    - Quick Start Guide:
      - 'Quick Start Guide': 'qsg.md'
    - Concepts:
      - 'Concepts': 'concepts.md'
    - Setup and Install:
      - Installation Guide:
        - 'Install in a VM': 'setup/install_in_vm.md'
        - 'Install in Docker': 'setup/install_in_docker.md'
        - 'Install in Kubernetes': 'setup/install_in_kubernetes.md'
      - Product Deployment:
        - 'Deploying WSO2 Enterprise Integrator' : 'setup/deploying_wso2_ei.md'
        - 'Upgrading from a Previous Release' : 'setup/upgrading.md'
        - Supporting Configurations:
          - 'Setting up a Load Balancer' : 'setup/setting_up_lb.md'
          - 'Setting up Databases' : 'setup/setting_up_db.md'
          - Setting up an LDAP/Active Directory:
            - 'Setting up a Read-Only LDAP' : 'setup/setting_up_ro_ldap.md'
            - 'Setting up a Read-Write LDAP' : 'setup/setting_up_rw_ldap.md'
            - 'Setting up a Read-Write Active Directory' : 'setup/setting_up_rw_ad.md'
          - 'Configuring Deployment Synchronization' : 'setup/deployment_synchronization.md'
          - 'Optional: Mounting a Registry' : 'setup/registry_mounting.md'
          - 'Creating New Keystores' : 'setup/creating_keystores.'
        - Security Hardening :
          - 'Configuring Keystores' : 'security/configuring_keystores.md'
          - 'Using Symmetric Encryption' : 'security/single_key_encryption.md'
          - 'Encrypting Plain Text' : 'security/encrypting_plain_text.md'
          - 'Mitigating Cross Site Request Forgery Attacks' : 'security/mitigating_csrf.md'
          - 'Mitigating Cross Site Scripting' : 'security/mitigating_css.md'
        - 'Backup and Recovery' : 'setup/backup_recovery.md'
        - 'Product Deployment Checklist' : 'setup/deployment_checklist.md'
        - Performance Tuning:
          - 'Tuning Database Performance' : 'setup/tuning_db_performance.md'
          - 'Tuning Network and OS Performance' : 'setup/network_os_performance.md'
    - Developer Experience:
      - 'Designing an Integration Use Case' : 'develop/design.md'
      - 'Testing an Integration Use Case' : 'develop/testing.md'
      - 'Continuous Development and Deployment' : 'develop/cicd.md'
    - Use Cases:
      - Samples:
        - 'Invoking a RESTful Service' : 'samples/invoking_restful_service.md'
      - Guides:
        - 'Message Routing' : 'guides/message_routing.md'
    - Administration and Observability:
      - 'User Management' : 'admin/user_management.md'
    - References:
      - 'Mediator Catalog' : 'ref/mediator_catalog.md'
      - 'Property Catalog' : 'ref/property_catalog.md'
      - 'Configuration Catalog' : 'ref/ei_config_catalog.md'
    - '': page-not-found.md
     
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    
# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 5.8.0
