# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Enterprise Integrator Documentation
site_description: Documentation for WSO2 Enterprise Integrator
site_author: WSO2
site_url: https://wso2.com/integration/

# Repository
repo_name: wso2/docs-ei
repo_url: https://github.com/wso2/docs-ei
edit_uri: https://github.com/wso2/docs-ei/edit/master/en/docs/

# Copyright
copyright: WSO2 Enterprise Integrator - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'
  
# Navigation
nav:
    - 'Home': index.md
    - Introduction:
      - 'Overview': 'overview/introduction.md'
      - 'Architecture': 'overview/architecture.md'
      - 'About this Release': 'overview/about-this-release.md'
    - Quick Start Guide:
      - 'Quick Start Guide': 'quick-start-guide/quick-start-guide.md'
    - Concepts:
      - 'Concepts': 'concepts/concepts.md'
    - Setup and Install:
      - Installation Guide:
        - 'Install in a VM': 'setup/installation/install_in_vm.md'
        - 'Install in Docker': 'setup/installation/install_in_docker.md'
        - 'Install in Kubernetes': 'setup/installation/install_in_kubernetes.md'
      - Product Deployment:
        - 'Deploying WSO2 Enterprise Integrator' : 'setup/deployment/deploying_wso2_ei.md'
        - 'Upgrading from a Previous Release' : 'setup/deployment/upgrading.md'
        - 'Troubleshooting Production Deployment' : 'setup/deployment/troubleshooting_deployment.md'
        - 'Product Deployment Checklist' : 'setup/deployment/deployment_checklist.md'
      - Using Data Stores:
        - Setting up Databases:
          - 'Setting up MySQL' : 'setup/databases/setting-up-MySQL.md'
          - 'Setting up MSSQL' : 'setup/databases/setting-up-MSSQL.md'
          - 'Setting up Oracle' : 'setup/databases/setting-up-Oracle.md'
          - 'Setting up Oracle RAC' : 'setup/databases/setting-up-Oracle-RAC.md'
          - 'Setting up IBM Informix' : 'setup/databases/setting-up-IBM-Informix.md'
          - 'Setting up IBM DB2' : 'setup/databases/setting-up-IBM-DB2.md'
          - 'Setting up Maria DB' : 'setup/databases/setting-up-MariaDB.md'
          - 'Setting up Embedded Derby' : 'setup/databases/setting-up-Embedded-Derby.md'
          - 'Setting up Remote Derby' : 'setup/databases/setting-up-Remote-Derby.md'
          - 'Setting up PostgreSQL' : 'setup/databases/setting-up-PostgreSQL.md'
          - 'Setting up Remote H2' : 'setup/databases/setting-up-Remote-H2.md'
        - Setting up a User Store:
          - 'Setting up a JDBC User Store' : 'setup/user_stores/setting_up_jdbc_userstore.md'
          - 'Setting up a Read-Only LDAP' : 'setup/user_stores/setting_up_ro_ldap.md'
          - 'Setting up a Read-Write LDAP' : 'setup/user_stores/setting_up_rw_ldap.md'
          - 'Setting up a Read-Write Active Directory' : 'setup/user_stores/setting_up_rw_ad.md'
      - Security Hardening :
        - Setting up Keystores:
          - 'Creating New Keystores' : 'setup/security/creating_keystores.md'
          - 'Adding SSL certificates to keystores' : 'setup/security/importing_ssl_certificate.md'
          - 'Renewing a CA-signed Certificate' : 'setup/security/renewing_ca_signed_certificate_in_keystore.md'
          - 'Configuring Keystores' : 'setup/security/configuring_keystores.md'
        - 'Complying with GDPR' : 'setup/security/gdpr_ei.md'
        - 'Using Symmetric Encryption' : 'setup/security/single_key_encryption.md'
        - 'Encrypting Plain Text' : 'setup/security/encrypting_plain_text.md'
        - 'Mitigating Cross Site Request Forgery Attacks' : 'setup/security/mitigating_csrf.md'
        - 'Mitigating Cross Site Scripting' : 'setup/security/mitigating_css.md'
        - 'Configuring SAML2 SSO Across Products' : 'setup/security/configuring_SAML2_SSO_across_prods.md'
        - 'Securing Carbon Applications' : 'setup/security/securing_carbon_applications.md'
      - Performance Tuning:
        - 'Tuning JVM Performance' : 'setup/performance_tuning/tuning_jvm_performance.md'
        - 'Tuning Network and OS Performance' : 'setup/performance_tuning/network_os_performance.md'
        - Tuning Use Cases:
          - 'Tuning the Split-Aggregator Pattern' : 'setup/performance_tuning/split_aggregate_pattern_tuning.md'
          - 'Tuning Message Transformation Scenarios' : 'setup/performance_tuning/message_transformation_tuning.md'
          - 'Tuning JMS Scenarios' : 'setup/performance_tuning/jms_scenarios.md'
          - 'Tuning Inbound Endpoints' : 'setup/performance_tuning/inbound_endpoint_tuning.md'
        - Tuning Transports:
          - 'Tuning the HTTP Transport' : 'setup/performance_tuning/http_transport_tuning.md'
          - 'Tuning the JMS Transport' : 'setup/performance_tuning/jms_transport_tuning.md'
          - 'Tuning the VFS Transport' : 'setup/performance_tuning/vfs_transport_tuning.md'
          - 'Tuning the RabbitMQ Transport' : 'setup/performance_tuning/rabbitmq_transport_tuning.md'
      - 'Backup and Recovery' : 'setup/backup_recovery.md'
      - Supporting Configurations:
        - 'Optional: Mounting a Registry': 'setup/registry_mounting.md'
        - 'Setting up a Load Balancer': 'setup/setting_up_lb.md'
        - 'Configuring Deployment Synchronization': 'setup/deployment_synchronization.md'
        - 'Adding a Custom Proxy Path': 'setup/adding_a_custom_proxy__path.md'
        - 'Configuring a Proxy Server': 'setup/configuring_proxy_servers.md'
        - 'Changing Default Ports': 'setup/changing_default_ports.md'
        - 'Enabling CORS for Data Services': 'setup/enabling_CORS_for_data_services.md'
        - 'Configuring Time Stamp Conversion for RDBMS': 'setup/configuring_timestamp_conversion_for_rdbms.md'
        - 'Customizing Error Messages': 'setup/customizing_error_pages.md'
        - 'Configuring the Task Scheduling Component': 'setup/configuring_task_scheduling_comp.md'
        - 'Governing External Reference Across Environments': 'setup/govern_ext_refs_across_env.md'
        - 'Enable SSL Tunneling through Proxy Server': 'setup/enabling_SSL_tunneling_thru_proxy_server.md'
    - Developer Experience:
      - 'Continuous Development and Deployment' : 'develop/cicd.md'
      - 'Developing an Integration Use Case' : 'develop/developing-Cloud-Native-Integration.md'
      - 'Testing an Integration Use Case' : 'develop/testing.md'
      - WSO2 Integration Studio:
        - 'WSO2 Integration Studio' : 'develop/wSO2-Integration-Studio.md'
        - 'Working with Integration Studio' : 'develop/working-with-WSO2-Integration-Studio.md'
        - 'Working with Mediators via Integration Studio' : 'develop/working-with-Mediators-via-Tooling.md'
    - Use Cases:
      - Samples:
        - 'Invoking a RESTful Service' : 'use-cases/guides.md'
      - Guides:
        - 'Message Routing' : 'guides/message_routing.md'
    - Administration and Observability:
      - 'Observability' : 'administer-and-observe/observability.md'
      - 'JMX Monitoring' : 'administer-and-observe/jmx_monitoring.md'
      - 'SNMP Monitoring' : 'administer-and-observe/snmp_monitoring.md'
      - 'Monitoring with Prometheus' : 'administer-and-observe/monitoring_with_prometheus.md'
      - Monitoring Logs:
        - 'About Logs' : 'administer-and-observe/monitoring_logs.md'
        - 'Monitoring Access Logs' : 'administer-and-observe/monitoring_access_logs.md'
        - 'Configuring Log4j Properties' : 'administer-and-observe/configuring_log4j_properties.md'
        - 'Configuring the Log Provider' : 'administer-and-observe/configuring_the_log_provider.md'
        - 'Masking Sensitive Information in Logs' : 'administer-and-observe/masking_sensitive_info_in_logs.md'
      - Monitoring TCP Messages:
        - 'Starting TCPMon' : 'administer-and-observe/starting_tcp_mon.md'
        - 'Message Monitoring with TCPMon' : 'administer-and-observe/message_monitoring_with_tcpmon.md'
        - 'Other Usages of TCPMon' : 'administer-and-observe/other_usages_of_tcpmon.md'
    - References:
      - 'Enterprise Integration Patterns' : 'references/enterprise-Integration-Patterns.md'
      - 'Configuration Catalog' : 'references/ei_config_catalog.md'
      - 'Mediator Catalog' : 
        - 'Mediator Catlog' : 'references/mediator_catalog.md'
        - 'ESB Mediators' : 
          - 'ESB Mediators' : 'references/eSB-Mediators.md'
          - 'Aggregate Mediators' : 'references/eSB-Mediators.md'
          - 'Bean Mediator' : 'references/eSB-Mediators.md'
          - 'Builder Mediator' : 'references/eSB-Mediators.md'
          - 'Cache Mediator' : 'references/eSB-Mediators.md'
          - 'Call Mediator' : 'references/eSB-Mediators.md'
          - 'Call Template Mediator' : 'references/eSB-Mediators.md'
          - 'Callout Mediator' : 'references/eSB-Mediators.md'
          - 'Class Mediator' : 'references/eSB-Mediators.md'
          - 'Clone Mediator' : 'references/eSB-Mediators.md'
          - 'Conditional Router Mediator' : 'references/eSB-Mediators.md'
          - 'Data Mapper Mediator' : 'references/eSB-Mediators.md'
          - 'DBLookup  Mediator' : 'references/eSB-Mediators.md'
          - 'DB Report Mediator' : 'references/eSB-Mediators.md'
          - 'Drop Mediator' : 'references/eSB-Mediators.md'
          - 'EJB Mediator' : 'references/eSB-Mediators.md'
          - 'Enqueue Mediator' : 'references/eSB-Mediators.md'
          - 'Enrich Mediator' : 'references/eSB-Mediators.md'
          - 'Entitlement Mediator' : 'references/eSB-Mediators.md'
          - 'Event Mediator' : 'references/eSB-Mediators.md'
          - 'FastXSLT Mediator' : 'references/eSB-Mediators.md'
          - 'Fault Mediator' : 'references/eSB-Mediators.md'
          - 'Filter Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'Header Mediator' : 'references/eSB-Mediators.md'
          - 'In and Out Mediator' : 'references/eSB-Mediators.md'
          - 'Iterate Mediator' : 'references/eSB-Mediators.md'
          - 'Log Mediator' : 'references/eSB-Mediators.md'
          - 'Loopback Mediator' : 'references/eSB-Mediators.md'
          - 'OAuth Mediator' : 'references/eSB-Mediators.md'
          - 'PayloadFactory Mediator' : 'references/eSB-Mediators.md'
          - 'POJOCommand Mediator' : 'references/eSB-Mediators.md'
          - 'Property Mediator' : 'references/eSB-Mediators.md'
          - 'Property Group Mediator' : 'references/eSB-Mediators.md'
          - 'Publish Event Mediator' : 'references/eSB-Mediators.md'
          - 'Respond Mediator' : 'references/eSB-Mediators.md'
          - 'Rule Mediator' : 'references/eSB-Mediators.md'
          - 'Script Mediator' : 'references/eSB-Mediators.md'
          - 'Send Mediator' : 'references/eSB-Mediators.md'
          - 'Sequence Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
          - 'ForEach Mediator' : 'references/eSB-Mediators.md'
      - 'Property Catalog' : 'references/property_catalog.md'
      - 'Best Practices' : 'references/best-Practices.md'
    - '': page-not-found.md
     
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    
# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 5.8.0
