# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Enterprise Integrator Documentation
site_description: Documentation for WSO2 Enterprise Integrator
site_author: WSO2
site_url: https://wso2.com/integration/

# Repository
repo_name: wso2/docs-ei
repo_url: https://github.com/wso2/docs-ei
edit_uri: https://github.com/wso2/docs-ei/edit/master/en/ballerina-integrator/docs/

# Copyright
copyright: WSO2 Enterprise Integrator - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'
  
# Navigation
nav:
    - 'Home': index.md
    - Getting Started:
      - 'Introduction': 'getting-started/introduction.md'
      - 'Quick Start Guide': 'getting-started/quick-start-guide.md'
    - Learn:
      - 'Overview': 'learn/about-learn.md'
      - Guides:
        - Messaging:
          - 'Asynchronous Messaging' : 'learn/guides/messaging/asynchronous-messaging/asynchronous-messaging.md'
          - 'Message Broadcasting' : 'learn/guides/messaging/message-broadcasting/message-broadcasting.md'
          - 'Messaging with ActiveMQ' : 'learn/guides/messaging/messaging-with-activemq/messaging-with-activemq.md'
          - 'Messaging with Kafka' : 'learn/guides/messaging/messaging-with-kafka/messaging-with-kafka.md'
          - 'Reliable Delivery' : 'learn/guides/messaging/reliable-delivery/reliable-delivery.md'
        - Services:
          - 'Exposing a REST Service' : 'learn/guides/services/restful-service/exposing-a-rest-service/exposing-a-rest-service.md'
          - 'Exposing a SOAP Service' : 'learn/guides/services/restful-service/exposing-a-soap-service/exposing-a-soap-service.md'
          - 'Service Composition' : 'learn/guides/services/service-composition/service-composition.md'
          - 'Asynchronous Invocation' : 'learn/guides/services/asynchronous-invocation/asynchronous-invocation.md'
          - 'Parallel Service Orchestration' : 'learn/guides/services/parallel-service-orchestration/parallel-service-orchestration.md'
        - Integration Patterns:
          - 'Content-based Routing' : 'learn/guides/integration-patterns/content-based-routing/content-based-routing.md'
          - 'Pass-through Messaging' : 'learn/guides/integration-patterns/pass-through-messaging/pass-through-messaging.md'
          - 'Scatter-gather Messaging' : 'learn/guides/integration-patterns/scatter-gather-messaging/scatter-gather-messaging.md'
          - 'Message Filtering' : 'learn/guides/integration-patterns/message-filtering/message-filtering.md'
          - 'Backend for Frontend' : 'learn/guides/integration-patterns/backend-for-frontend/backend-for-frontend.md'
          - 'EIP Message Construction' : 'learn/guides/integration-patterns/eip-message-construction/eip-message-construction.md'
          - 'EIP Message Transformation' : 'learn/guides/integration-patterns/eip-message-transformation/eip-message-transformation.md'
        - Database Integration:
          - 'Data-backed Service' : 'learn/guides/database-integrations/data-backed-service/data-backed-service.md'
          - 'Managing Database Transactions' : 'learn/guides/database-integrations/managing-database-transactions/managing-database-transactions.md'
          - 'Integration with MongoDB' : 'learn/guides/database-integrations/mongo/mongo.md'
      - Tutorials:
        - 'Sending a Simple Message to a Service' : 'learn/integration-tutorials/sending-a-simple-message-to-a-service/README.md'
        - 'Sending a Simple Message to a Datasource' : 'learn/integration-tutorials/sending-a-simple-message-to-a-datasource/README.md'
        - 'Routing Requests Based on Message Content' : 'learn/integration-tutorials/routing-requests-based-on-message-content/README.md'
        - 'Transforming Message Content' : 'learn/integration-tutorials/transforming-message-content/README.md'
        - 'Exposing Several Services as a Single Service' : 'learn/integration-tutorials/exposing-several-services-as-a-single-service/README.md'
        - 'Storing and Forwarding Messages' : 'learn/integration-tutorials/storing-and-forwarding-messages/README.md'
        - 'Using the Gmail Connector' : 'learn/integration-tutorials/using-the-gmail-connector/README.md'
        - 'Using the Analytics Dashboard' : 'learn/integration-tutorials/using-the-analytics-dashboard/README.md'
    - Develop:
      - 'Re-introducing Ballerina Programming Language' : 'develop/reintroducing-ballerina.md'
      - 'Setting up the Developer Environment' : 'develop/setup-dev.md'
      - 'Creating a Project' : 'develop/using-modules.md'
      - 'Working with VS Code' : 'develop/working-with-vscode.md'
    - Deploy:
      - 'Deploying on Docker': 'deploy/deploy-on-docker.md'
      - 'Deploying on Kubernetes': 'deploy/deploy-on-kubernetes.md'
      - 'Running as a Java Program': 'deploy/running-as-a-java-program.md'
      - 'CI/CD' : 'deploy/cicd.md'
    - Observe:
      - 'Observing a Service with Prometheus' : 'observe/observing-a-service.md'
      - 'Logging using logstash and Kibana' : 'observe/logstash-kibana.md'
    - References:
      - 'References' : 'references/references.md'
    - '': page-not-found.md
     
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    
# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 7.0.0
